site_name: Workshop Unittest

nav:
    - Home: index.md
    - About Unittest: about_unittest.md
    - Let's do it: lets_do_it.md

theme:
    name: material

plugins:
    - search
    - mermaid2:
        arguments:
            theme: 'dark'

extra_javascript:
    - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js